# [START cloudbuild_start_data_fusion_pipeline]
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud datafusion pipelines start PIPELINE_NAME \
          --project=PROJECT_ID \
          --region=REGION \
          --instance=DATA_FUSION_INSTANCE_NAME
# [END cloudbuild_start_data_fusion_pipeline]

# [START cloudbuild_start_composer_dag]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud composer environments run ENVIRONMENT_NAME \
          --location=LOCATION \
          --project=PROJECT_ID \
          -- "trigger_dag" "--conf" "{\"dag_id\":\"DAG_ID\"}"
# [END cloudbuild_start_composer_dag]
