# [START cloudbuild_start_data_fusion_pipeline]
steps:
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        access_token="$(gcloud auth print-access-token)"
        url="https://datafusion.googleapis.com/v1/projects/savvy-hull-383206/locations/europe-west6/instances/demo-instance/pipelines/main_pipeline2:start"
        curl -X POST -H "Authorization: Bearer $access_token" "$url"
# [END cloudbuild_start_data_fusion_pipeline]

# [START cloudbuild_start_composer_dag]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud composer environments run demo-composer --location europe-west6 --project=savvy-hull-383206 --execute -- "trigger_dag" "--" "--conf" "{\"dag_id\":\"dataproc_cluster_jobs_3\"}"
# [END cloudbuild_start_composer_dag]
